- releng/org.polarsys.capella.docgen.target/tp/capella.target-definition.target
- releng/org.polarsys.capella.docgen.target/tp/capella.target-definition.targetplatform
Signed-off-by: Thomas Guiu <thomas.guiu@soyatec.com>
> [releng] update TP

- docgenhtml/features/org.polarsys.capella.docgen.configuration.feature/feature.xml
- docgenhtml/features/org.polarsys.capella.docgen.feature/feature.xml
- docgenhtml/features/org.polarsys.capella.docgen.package.feature/feature.xml
- docgenhtml/features/pom.xml
- docgenhtml/plugins/org.polarsys.capella.docgen.commandline/META-INF/MANIFEST.MF
- docgenhtml/plugins/org.polarsys.capella.docgen.configuration.commandline/META-INF/MANIFEST.MF
- docgenhtml/plugins/org.polarsys.capella.docgen.configuration.edit/META-INF/MANIFEST.MF
- docgenhtml/plugins/org.polarsys.capella.docgen.configuration.editor/META-INF/MANIFEST.MF
- docgenhtml/plugins/org.polarsys.capella.docgen.configuration.ui/META-INF/MANIFEST.MF
- docgenhtml/plugins/org.polarsys.capella.docgen.configuration/META-INF/MANIFEST.MF
- docgenhtml/plugins/org.polarsys.capella.docgen.preference/META-INF/MANIFEST.MF
- docgenhtml/plugins/org.polarsys.capella.docgen.ui/META-INF/MANIFEST.MF
- docgenhtml/plugins/org.polarsys.capella.docgen/META-INF/MANIFEST.MF
- docgenhtml/plugins/pom.xml
- pom.xml
- releng/org.polarsys.capella.docgen.site/category.xml
- releng/org.polarsys.capella.docgen.site/pom.xml
- releng/org.polarsys.capella.docgen.target/pom.xml
Signed-off-by: Thomas Guiu <thomas.guiu@soyatec.com>
> [releng] bump to 1.3.3

- releng/org.polarsys.capella.docgen.target/tp/capella.target-definition.target
- releng/org.polarsys.capella.docgen.target/tp/capella.target-definition.targetplatform
Change-Id: Ifffd83ea9eca17599419f165016bc0fecd88aea1
> [releng] Update TP for 1.4.1.IT4

- docgenhtml/plugins/org.polarsys.capella.docgen/generated/org/polarsys/capella/docgen/content/RegionDocGen.java
- docgenhtml/plugins/org.polarsys.capella.docgen/templates/pattern._1fzXsL9JEeC3itjHQ6nPuA/method._A5FHED4pEeKDPO8mQtK38g.pt
Tigger -> Trigger
Bug: 565115
Change-Id: I10e20a8713eaa028715bc8b1f758283dc5698bd5
> [565115] Typo correction

- docgenhtml/plugins/org.polarsys.capella.docgen/src/org/polarsys/capella/docgen/util/ImageHelper.java
- docgenhtml/plugins/org.polarsys.capella.docgen/src/org/polarsys/capella/docgen/util/StringUtil.java
- releng/org.polarsys.capella.docgen.site/.project
- releng/org.polarsys.capella.docgen.target/tp/capella.target-definition.target
- releng/org.polarsys.capella.docgen.target/tp/capella.target-definition.targetplatform
This PR contains corrections for the richtext documentation content handling in documentation generation.
This includes: 
- b8c8dc4 : a bug found on the handling of images/files links with special characters in their path.
- ff9fa3e : support of embedded images by serializing them to image files
A target platform update was necessary to get the code to compile (416fad4).
An additional small modification on a project name is also included (0d06801).
> Embedded images documentation

- docgenhtml/plugins/org.polarsys.capella.docgen/META-INF/MANIFEST.MF
Change-Id: I64d54d64f1c642a23de0dc759e038f2e0b93f083
> [releng] Bump 1.4.2 - missed plugin version update

- docgenhtml/features/org.polarsys.capella.docgen.configuration.feature/feature.xml
- docgenhtml/features/org.polarsys.capella.docgen.feature/feature.xml
- docgenhtml/features/org.polarsys.capella.docgen.package.feature/feature.xml
- docgenhtml/features/pom.xml
- docgenhtml/plugins/org.polarsys.capella.docgen.commandline/META-INF/MANIFEST.MF
- docgenhtml/plugins/org.polarsys.capella.docgen.configuration.commandline/META-INF/MANIFEST.MF
- docgenhtml/plugins/org.polarsys.capella.docgen.configuration.edit/META-INF/MANIFEST.MF
- docgenhtml/plugins/org.polarsys.capella.docgen.configuration.editor/META-INF/MANIFEST.MF
- docgenhtml/plugins/org.polarsys.capella.docgen.configuration.ui/META-INF/MANIFEST.MF
- docgenhtml/plugins/org.polarsys.capella.docgen.configuration/META-INF/MANIFEST.MF
- docgenhtml/plugins/org.polarsys.capella.docgen.preference/META-INF/MANIFEST.MF
- docgenhtml/plugins/org.polarsys.capella.docgen.ui/META-INF/MANIFEST.MF
- docgenhtml/plugins/org.polarsys.capella.docgen/META-INF/MANIFEST.MF
- docgenhtml/plugins/pom.xml
- pom.xml
- releng/org.polarsys.capella.docgen.site/pom.xml
- releng/org.polarsys.capella.docgen.target/pom.xml
Change-Id: Ic448634d022dcff14f4fe1a825178b32e71af19f
> [releng] Bump to 1.4.3

- releng/org.polarsys.capella.docgen.target/tp/capella.target-definition.target
- releng/org.polarsys.capella.docgen.target/tp/capella.target-definition.targetplatform
Change-Id: I27e82ef551c68f5e27aa338055352bbf2bbe26de
> [releng] Update TP for 5.0.0

- Jenkinsfile
- docgenhtml/plugins/org.polarsys.capella.docgen/src/org/polarsys/capella/docgen/util/SortedTreeNode.java
- docgenhtml/plugins/org.polarsys.capella.docgen/src/org/polarsys/capella/docgen/util/TreeServices.java
- pom.xml
- releng/org.polarsys.capella.docgen.target/tp/capella.target-definition.target
- releng/org.polarsys.capella.docgen.target/tp/capella.target-definition.targetplatform
- Update code
Change-Id: I2cecf96d732d7a952e5454e8f81d9bcd1a7d14f6
> [releng] Update java version to 14 and Tycho to 2.0

- docgenhtml/plugins/org.polarsys.capella.docgen.commandline/src/org/polarsys/capella/docgen/commandline/HTMLCommandLine.java
- docgenhtml/plugins/org.polarsys.capella.docgen.configuration.commandline/src/org/polarsys/capella/docgen/configuration/commandline/HTMLConfigurationCommandLine.java
- docgenhtml/plugins/org.polarsys.capella.docgen/src/org/polarsys/capella/docgen/diagram/CapellaHelper.java
Bug: 567412
Change-Id: Ie2a55ba967320d3c931ba97018ec0e11ab6b88d0
> [567412] Change extension from melodymodeller to capella

- releng/org.polarsys.capella.docgen.target/tp/capella.target-definition.target
- releng/org.polarsys.capella.docgen.target/tp/capella.target-definition.targetplatform
Change-Id: I0000000000000000000000000000000000000000
> [releng] Update TP - 5.0.0-IT1

- docgenhtml/features/org.polarsys.capella.docgen.configuration.feature/feature.xml
- docgenhtml/features/org.polarsys.capella.docgen.feature/feature.xml
- docgenhtml/features/org.polarsys.capella.docgen.package.feature/feature.xml
- docgenhtml/features/pom.xml
- docgenhtml/plugins/org.polarsys.capella.docgen.commandline/META-INF/MANIFEST.MF
- docgenhtml/plugins/org.polarsys.capella.docgen.configuration.commandline/META-INF/MANIFEST.MF
- docgenhtml/plugins/org.polarsys.capella.docgen.configuration.edit/META-INF/MANIFEST.MF
- docgenhtml/plugins/org.polarsys.capella.docgen.configuration.editor/META-INF/MANIFEST.MF
- docgenhtml/plugins/org.polarsys.capella.docgen.configuration.ui/META-INF/MANIFEST.MF
- docgenhtml/plugins/org.polarsys.capella.docgen.configuration/META-INF/MANIFEST.MF
- docgenhtml/plugins/org.polarsys.capella.docgen.preference/META-INF/MANIFEST.MF
- docgenhtml/plugins/org.polarsys.capella.docgen.ui/META-INF/MANIFEST.MF
- docgenhtml/plugins/org.polarsys.capella.docgen/META-INF/MANIFEST.MF
- docgenhtml/plugins/pom.xml
- pom.xml
- releng/org.polarsys.capella.docgen.site/category.xml
- releng/org.polarsys.capella.docgen.site/pom.xml
- releng/org.polarsys.capella.docgen.target/pom.xml
Change-Id: I9b4f7a5b88a27bcbfde5b788b693b64c6c611ce1
> [releng] Bump to 5.0.0

- releng/org.polarsys.capella.docgen.target/tp/capella.target-definition.target
- releng/org.polarsys.capella.docgen.target/tp/capella.target-definition.targetplatform
Change-Id: Ica4fff9fd5cfc18be577df55fb254bac1731a04a
> [releng] Update TP to Capella 5.0.0-IT1

- releng/org.polarsys.capella.docgen.target/tp/capella.target-definition.target
- releng/org.polarsys.capella.docgen.target/tp/capella.target-definition.targetplatform
Change-Id: If9f27f8795e0f2d3ed8a940b6774fa03e5521fc9
> [releng] Update TP for 5.0.0-IT3

- docgenhtml/plugins/org.polarsys.capella.docgen.configuration.edit/icons/full/obj16/license.txt
- docgenhtml/plugins/org.polarsys.capella.docgen.configuration.editor/icons/full/obj16/license.txt
- docgenhtml/plugins/org.polarsys.capella.docgen.configuration.editor/icons/full/wizban/license.txt
- docgenhtml/plugins/org.polarsys.capella.docgen.configuration.ui/icons/full/ctool16/license.txt
- docgenhtml/plugins/org.polarsys.capella.docgen.ui/icons/full/ctool16/license.txt
- docgenhtml/plugins/org.polarsys.capella.docgen.ui/icons/license.txt
- tests/plugins/org.eclipse.capella.docgen.test.rcptt/icons/license.txt
Change-Id: Iddef94f1033ce5110c16d878cac209685f1d0612
> [568919] Update license.txt files

- releng/org.polarsys.capella.docgen.target/tp/capella.target-definition.target
- releng/org.polarsys.capella.docgen.target/tp/capella.target-definition.targetplatform
Change-Id: I93305051f87bb9eec363b2e9ec6f55c40d3db179
> [releng] Update TP for release 5.0.0

- docgenhtml/plugins/org.polarsys.capella.docgen/src/org/polarsys/capella/docgen/util/ImageHelper.java
- docgenhtml/plugins/org.polarsys.capella.docgen/src/org/polarsys/capella/docgen/util/StringUtil.java
- releng/org.polarsys.capella.docgen.target/tp/capella.target-definition.target
- releng/org.polarsys.capella.docgen.target/tp/capella.target-definition.targetplatform
* #154 Broken file/image links in description causes generation failing
[569542]
* #157 Handle images references using UNC path [569852]
- Ensure unique file names for copied images
- Handle encoded URI strings in description
- Handle UNC path
* #158 Handle http(s) references
Change-Id: I9df88c64b94f1d2516857a8ccfaeaf9745525f81
> #154 #157 #158 report commits

- docgenhtml/plugins/org.polarsys.capella.docgen.commandline/plugin.properties
- docgenhtml/plugins/org.polarsys.capella.docgen.doc/plugin.properties
- releng/org.polarsys.capella.docgen.target/tp/capella.target-definition.target
- releng/org.polarsys.capella.docgen.target/tp/capella.target-definition.targetplatform
Change-Id: I7c76d68a52f3ad717047fee4ff78013713d7fbb0
> #159 Fix branding

- releng/org.polarsys.capella.docgen.target/tp/capella.target-definition.target
- releng/org.polarsys.capella.docgen.target/tp/capella.target-definition.targetplatform
Change-Id: Id71d15364824fd5ff66a0583cf62397d002a9f3d
> [releng] Update TP for 5.1.0 - IT2

- pom.xml
- releng/org.polarsys.capella.docgen.site/category.xml
- releng/org.polarsys.capella.docgen.target/tp/capella.target-definition.target
- releng/org.polarsys.capella.docgen.target/tp/capella.target-definition.targetplatform
Change-Id: Ia010c1161732ffbb3ebdea4878ec568873414a66
> #97 Include sources in packaging

- docgenhtml/plugins/org.polarsys.capella.docgen/egf/HTMLDocGenCapella.fcore
- docgenhtml/plugins/org.polarsys.capella.docgen/generated/org/polarsys/capella/docgen/content/CategoriesDocGen.java
- docgenhtml/plugins/org.polarsys.capella.docgen/generated/org/polarsys/capella/docgen/foundations/AllConstraintsDocGen.java
- docgenhtml/plugins/org.polarsys.capella.docgen/generated/org/polarsys/capella/docgen/foundations/CapellaElementEndContentDocGen.java
- docgenhtml/plugins/org.polarsys.capella.docgen/generated/org/polarsys/capella/docgen/foundations/ConstraintsDocGen.java
- docgenhtml/plugins/org.polarsys.capella.docgen/generated/org/polarsys/capella/docgen/foundations/PropertyValueGen.java
- docgenhtml/plugins/org.polarsys.capella.docgen/src/org/polarsys/capella/docgen/util/CapellaServices.java
- docgenhtml/plugins/org.polarsys.capella.docgen/src/org/polarsys/capella/docgen/util/ConstraintsService.java
- docgenhtml/plugins/org.polarsys.capella.docgen/src/org/polarsys/capella/docgen/util/pattern/helper/PropertyValueHelper.java
- docgenhtml/plugins/org.polarsys.capella.docgen/templates/pattern._B0Sp4FxqEemRLucKv8z86A/method._B0Sp5FxqEemRLucKv8z86A.pt
- docgenhtml/plugins/org.polarsys.capella.docgen/templates/pattern._F9HPoVcEEeWXKstRBeKifA/method._F9HPo1cEEeWXKstRBeKifA.pt
- docgenhtml/plugins/org.polarsys.capella.docgen/templates/pattern._F9HPoVcEEeWXKstRBeKifA/method._F9HPplcEEeWXKstRBeKifA.pt
- docgenhtml/plugins/org.polarsys.capella.docgen/templates/pattern._H6iekavLEeCas-LHcur3rg/method._H6ielqvLEeCas-LHcur3rg.pt
- docgenhtml/plugins/org.polarsys.capella.docgen/templates/pattern._MribAMILEeu7XfnfLZ0e8g/method._MribA8ILEeu7XfnfLZ0e8g.pt
- docgenhtml/plugins/org.polarsys.capella.docgen/templates/pattern._MribAMILEeu7XfnfLZ0e8g/method._MribAsILEeu7XfnfLZ0e8g.pt
- docgenhtml/plugins/org.polarsys.capella.docgen/templates/pattern._MribAMILEeu7XfnfLZ0e8g/method._MribBcILEeu7XfnfLZ0e8g.pt
- docgenhtml/plugins/org.polarsys.capella.docgen/templates/pattern._UT85gDr2EeK9AZkoGpWdMw/method._UT85gjr2EeK9AZkoGpWdMw.pt
- docgenhtml/plugins/org.polarsys.capella.docgen/templates/pattern._UT85gDr2EeK9AZkoGpWdMw/method._UT85hTr2EeK9AZkoGpWdMw.pt
Report modifications from master to 1.4.x
> #152 #177 #180 #183 Report to 1.4.x

- docgenhtml/features/org.polarsys.capella.docgen.configuration.feature/feature.properties
- docgenhtml/features/org.polarsys.capella.docgen.feature/feature.properties
- docgenhtml/features/org.polarsys.capella.docgen.package.feature/feature.properties
- docgenhtml/plugins/org.polarsys.capella.docgen.commandline/plugin.properties
- docgenhtml/plugins/org.polarsys.capella.docgen.configuration.commandline/plugin.properties
- docgenhtml/plugins/org.polarsys.capella.docgen.configuration.edit/plugin.properties
- docgenhtml/plugins/org.polarsys.capella.docgen.configuration.editor/plugin.properties
- docgenhtml/plugins/org.polarsys.capella.docgen.configuration.ui/plugin.properties
- docgenhtml/plugins/org.polarsys.capella.docgen.configuration/plugin.properties
- docgenhtml/plugins/org.polarsys.capella.docgen.doc/plugin.properties
- docgenhtml/plugins/org.polarsys.capella.docgen.preference/plugin.properties
- docgenhtml/plugins/org.polarsys.capella.docgen.ui/plugin.properties
- docgenhtml/plugins/org.polarsys.capella.docgen/plugin.properties
- releng/org.polarsys.capella.docgen.target/tp/capella.target-definition.target
- releng/org.polarsys.capella.docgen.target/tp/capella.target-definition.targetplatform
Change-Id: Icf1ea1ef2cfbdd0e6eeb1091a9bd61766074c19d
> #187 Harmonize plugin display names

- docgenhtml/features/org.polarsys.capella.docgen.configuration.feature/feature.properties
- docgenhtml/features/org.polarsys.capella.docgen.configuration.feature/feature.xml
- docgenhtml/features/org.polarsys.capella.docgen.feature/feature.properties
- docgenhtml/features/org.polarsys.capella.docgen.feature/feature.xml
- docgenhtml/features/org.polarsys.capella.docgen.package.feature/feature.properties
- docgenhtml/features/org.polarsys.capella.docgen.package.feature/feature.xml
- docgenhtml/features/pom.xml
- docgenhtml/plugins/org.polarsys.capella.docgen.commandline/META-INF/MANIFEST.MF
- docgenhtml/plugins/org.polarsys.capella.docgen.commandline/plugin.properties
- docgenhtml/plugins/org.polarsys.capella.docgen.configuration.commandline/META-INF/MANIFEST.MF
- docgenhtml/plugins/org.polarsys.capella.docgen.configuration.commandline/plugin.properties
- docgenhtml/plugins/org.polarsys.capella.docgen.configuration.edit/META-INF/MANIFEST.MF
- docgenhtml/plugins/org.polarsys.capella.docgen.configuration.edit/plugin.properties
- docgenhtml/plugins/org.polarsys.capella.docgen.configuration.editor/META-INF/MANIFEST.MF
- docgenhtml/plugins/org.polarsys.capella.docgen.configuration.editor/plugin.properties
- docgenhtml/plugins/org.polarsys.capella.docgen.configuration.ui/META-INF/MANIFEST.MF
- docgenhtml/plugins/org.polarsys.capella.docgen.configuration.ui/plugin.properties
- docgenhtml/plugins/org.polarsys.capella.docgen.configuration/META-INF/MANIFEST.MF
- docgenhtml/plugins/org.polarsys.capella.docgen.configuration/plugin.properties
- docgenhtml/plugins/org.polarsys.capella.docgen.preference/META-INF/MANIFEST.MF
- docgenhtml/plugins/org.polarsys.capella.docgen.preference/plugin.properties
- docgenhtml/plugins/org.polarsys.capella.docgen.ui/META-INF/MANIFEST.MF
- docgenhtml/plugins/org.polarsys.capella.docgen.ui/plugin.properties
- docgenhtml/plugins/org.polarsys.capella.docgen/META-INF/MANIFEST.MF
- docgenhtml/plugins/org.polarsys.capella.docgen/plugin.properties
- docgenhtml/plugins/pom.xml
- pom.xml
- releng/org.polarsys.capella.docgen.site/pom.xml
- releng/org.polarsys.capella.docgen.target/pom.xml
- Bump to version 1.4.5 for Capella 1.4.2
- Fix a plugin branding
Change-Id: I3bc832242e4bb24b6890cdb10f2b87df529c5a5c
> [releng] Bump to 1.4.5

- releng/org.polarsys.capella.docgen.target/tp/capella.target-definition.target
- releng/org.polarsys.capella.docgen.target/tp/capella.target-definition.targetplatform
Change-Id: If8efc117d3cddbca874dcc014eadbd5edd138a8e
> [releng] Update TP for Capella 5.1.0 IT4

- releng/org.polarsys.capella.docgen.target/tp/capella.target-definition.target
- releng/org.polarsys.capella.docgen.target/tp/capella.target-definition.targetplatform
Kitalpha 5.1.0 release
Capella 5.1.0 release
Change-Id: Iaed75c606faf460dad83a6a25fc547d25c63a3a8
> [releng] Update TP to Kitalpha and Capella releases

- docgenhtml/features/org.polarsys.capella.docgen.configuration.feature/feature.xml
- docgenhtml/features/org.polarsys.capella.docgen.feature/feature.xml
- docgenhtml/features/org.polarsys.capella.docgen.package.feature/feature.xml
- docgenhtml/features/pom.xml
- docgenhtml/plugins/org.polarsys.capella.docgen.commandline/META-INF/MANIFEST.MF
- docgenhtml/plugins/org.polarsys.capella.docgen.configuration.commandline/META-INF/MANIFEST.MF
- docgenhtml/plugins/org.polarsys.capella.docgen.configuration.edit/META-INF/MANIFEST.MF
- docgenhtml/plugins/org.polarsys.capella.docgen.configuration.editor/META-INF/MANIFEST.MF
- docgenhtml/plugins/org.polarsys.capella.docgen.configuration.ui/META-INF/MANIFEST.MF
- docgenhtml/plugins/org.polarsys.capella.docgen.configuration/META-INF/MANIFEST.MF
- docgenhtml/plugins/org.polarsys.capella.docgen.doc/META-INF/MANIFEST.MF
- docgenhtml/plugins/org.polarsys.capella.docgen.preference/META-INF/MANIFEST.MF
- docgenhtml/plugins/org.polarsys.capella.docgen.ui/META-INF/MANIFEST.MF
- docgenhtml/plugins/org.polarsys.capella.docgen/META-INF/MANIFEST.MF
- docgenhtml/plugins/org.polarsys.capella.docgen/generated/org/polarsys/capella/docgen/foundations/CapellaElementContentDocGen.java
- docgenhtml/plugins/org.polarsys.capella.docgen/src/org/polarsys/capella/docgen/util/StringUtil.java
- docgenhtml/plugins/org.polarsys.capella.docgen/templates/pattern._2twVYKu9EeCWrf9pgx3zjA/method._2twVZau9EeCWrf9pgx3zjA.pt
- docgenhtml/plugins/pom.xml
- pom.xml
- releng/org.polarsys.capella.docgen.site/category.xml
- releng/org.polarsys.capella.docgen.site/pom.xml
- releng/org.polarsys.capella.docgen.target/pom.xml
- releng/org.polarsys.capella.docgen.target/tp/capella.target-definition.target
- releng/org.polarsys.capella.docgen.target/tp/capella.target-definition.targetplatform
Migrate TP to include:
- Kitalpha 6.0
- Capella 6.0
- Nattable 2.0.1
- Nebula 2.3.0
Jarsigner update
Report #196 from master
Bump to 6.0.0
Change-Id: Id11992a29e5204baa9305fb11f58f6dd9e13750b
> [releng] Migration 2021-06 - Kitalpha impacts

- releng/org.polarsys.capella.docgen.target/tp/capella.target-definition.targetplatform
Change-Id: I923f427e98ba40e6a00694e7815ba3c17a43c6e8
Signed-off-by: Philippe DUL <philippe.dul@thalesgroup.com>
> [releng] Update Target platform (#220)

- releng/org.polarsys.capella.docgen.target/tp/capella.target-definition.targetplatform
Change-Id: I87e6384e6095d49e891d6e812cdb891d3261ab5d
Signed-off-by: Philippe DUL <philippe.dul@thalesgroup.com>
> [releng] Update Target platform

- docgenhtml/plugins/org.polarsys.capella.docgen/src/org/polarsys/capella/docgen/util/CapellaServices.java
Change-Id: Ife7acf8738cd5f77cbc899c832152c920f18ad01
> #239 Change visibility of Hyperlink String constants

- docgenhtml/plugins/org.polarsys.capella.docgen.configuration.ui/src/org/polarsys/capella/docgen/configuration/ui/viewer/providers/DetailsLabelProvider.java
- docgenhtml/plugins/org.polarsys.capella.docgen/src/org/polarsys/capella/docgen/util/CDOImageHandler.java
- docgenhtml/plugins/org.polarsys.capella.docgen/src/org/polarsys/capella/docgen/util/DefaultImageHandler.java
- docgenhtml/plugins/org.polarsys.capella.docgen/src/org/polarsys/capella/docgen/util/IImageHandler.java
- docgenhtml/plugins/org.polarsys.capella.docgen/src/org/polarsys/capella/docgen/util/ImageHandlerService.java
- docgenhtml/plugins/org.polarsys.capella.docgen/src/org/polarsys/capella/docgen/util/StringUtil.java
- releng/org.polarsys.capella.docgen.target/tp/capella.target-definition.targetplatform
Added docgen team feature & plugin that provide a CDOImageHandler which properly handles images with cdo URI, by returning the path of the temp image
Change-Id: Id025f2e410e9fc99cd7f4877ad737f56eb91d132
> #243 Images are now properly exported from remote cdo projects

- docgenhtml/plugins/org.polarsys.capella.docgen.configuration.ui/src/org/polarsys/capella/docgen/configuration/ui/wizard/SelectElementsWizardPage.java
Fixed small issue where button images weren't disposed properly on wizard closure
Change-Id: I5f9203b03dcaeb14978ab53b040dfab913344926
> #249 Selection is now initialized in DocGen wizard

- docgenhtml/plugins/org.polarsys.capella.docgen.configuration.ui/src/org/polarsys/capella/docgen/configuration/ui/viewer/providers/DetailsLabelProvider.java
Change-Id: I85ad324c6a5931ea0385abc58d915139e4d31cd5
> #251 Fix DocGen wizard so that semantic provider isn't disposed

- Jenkinsfile
- pom.xml
Set sonar java version to 17
Change-Id: I6fe93573d4271dd1af6ceeb51b5974b0346903ed
> [sonar] Update organization

- pom.xml
Sonar did not find modules because of this
Change-Id: Idd890237a173bf0e59351644cea7b429ff746a7b
> [sonar] Add activeByDefault in full profile

- docgenhtml/plugins/org.polarsys.capella.docgen.doc/html/Installation and Uninstall.html
- docgenhtml/plugins/org.polarsys.capella.docgen.doc/html/Installation and Uninstall.mediawiki
- docgenhtml/plugins/org.polarsys.capella.docgen.doc/html/Release Notes/KnownIssues.html
- docgenhtml/plugins/org.polarsys.capella.docgen.doc/html/Release Notes/KnownIssues.mediawiki
- docgenhtml/plugins/org.polarsys.capella.docgen.doc/html/Release Notes/Whatsnew.html
- docgenhtml/plugins/org.polarsys.capella.docgen.doc/html/Release Notes/Whatsnew.mediawiki
- docgenhtml/plugins/org.polarsys.capella.docgen.doc/html/common/capella-docgen-extensions.html
- docgenhtml/plugins/org.polarsys.capella.docgen.doc/html/common/capella-docgen-extensions.mediawiki
update eclipse to eclipse-capella
Change-Id: Id5a581d01eb681ba63ccdcef52cbdb4b5e93e908
> [releng] Update links to github
